name: Build
on: [push, pull_request]
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
     - name: Install alsa
       run: sudo apt-get install libasound2-dev
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-10.15, ubuntu-latest]
    steps:
     - uses: actions/checkout@v2
     - name: Build
       run: cargo build --verbose
      
