on: [push, pull_request]
name: Clippy check
jobs:
  clippy_check:
    runs-on: ubuntu-latest
    steps:
      - name: Install alsa
        run: sudo apt-get install libasound2-dev
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
            components: clippy
            override: true
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
